### ISSUE TITLE
"rescheduling didn't change the due date of the card. Is the add-on ReMemorized installed and activated?"

### ISSUE THREAD

**Issue by fibushj** [ijgnd/anki__reviewer_Alternative_Dialog_for_ReMemorize#3]
Hello,
The addon worked for me a week ago perfectly, but now for some reason I receive the above message.
Tried to reinstall but didn't work unfortunately.

**Comment by ijgnd** [comment]
You don't offer enough details. Did something change in the last week, installed new add-ons or updated them? Also interesting: https://anki.tenderapp.com/kb/problems/when-problems-occur  

I just made a few changes. Maybe they fixed your problem by accident .... Could you try it out: 

- uninstall the current version of my add-on
- download the new version from [here](https://github.com/ijgnd/anki__reviewer_Alternative_Dialog_for_ReMemorize/releases/download/2019-10-08/anki__reviewer_Alternative_Dialog_for_ReMemorize__21__2019-10-08.ankiaddon)
- install it as show in [this video](https://raw.githubusercontent.com/glutanimate/docs/master/anki/add-ons/media/ankiaddon-installation.gif).

Do you still have this problem? For me it works if I use the latest anki version (2.1.15) and the latest version of rememorize. Could you try with only these two add-ons to rule out interference.

**Comment by fibushj** [comment]
Thank you for the reply.
I didn't change Anki in any way during the last week (actually, I wasn't active in Anki during that week).
I followed your instructions and downdloaded your new version of but unfortunately the problem wasn't solved. I also disabled all the other addons and restarted the computer, but it doesn't help :(

**Comment by ijgnd** [comment]
- if you do not use the latest version of anki which is 2.1.15 update and try again
- update all your add-ons in 2.1 to make sure that you have the latest version of rememorize
- install the add-on [Extended Card Stats During Review](https://ankiweb.net/shared/info/1008566916) and restart
- disable my add-on and restart Anki. Then use the rememorize add-on to change the scheduling. Does it work as expected? You can check in the sidebar of the add-on Extended Card Stats.
- Does this happen for all cards or only for certain cards or only one card?

**Comment by fibushj** [comment]
It happends for all the cards, and I have the latest version of everything. 
I've just tried the original version of Rememorize, and I'll probably stick with it since it works well. Thank you very much for the help!

**Comment by fibushj** [comment]
It happends for all the cards, and I have the latest version of everything.
I've just tried the original version of Rememorize, and I'll probably stick with it since it works well. Thank you very much for the help!
